---
- hosts: all
  sudo: yes
  tasks:
    - name: Install the MySQL packages
      apt: name={{ item }} state=installed update_cache=yes
      with_items:
         - mysql-server-5.6
         - mysql-client-5.6
         - python-mysqldb
         - libmysqlclient-dev 
